import { Injectable } from '@angular/core';
import {APIService} from "../apiservice/apiservice.service";
import {HttpClient} from "@angular/common/http";
import {SessionService} from "../session/session.service";
import {Router} from "@angular/router";
import {Observable, of} from "rxjs";
import {NewsArticle} from "../../entities/NewsArticle";
import { environment } from 'src/environments/environment';

@Injectable({
  providedIn: 'root'
})
export class NewsArticleService extends APIService {

  constructor(http: HttpClient, sessionService: SessionService, router: Router) {
    super(http, sessionService, router);
  }

  getLatestArticles(limit: number): Observable<NewsArticle[]> {
   // return this.getData<NewsArticle[]>('news-articles/latest/'+limit)
    return of([
      {
        "id": 3,
        "name": "Leave the Game, Suspend Characters",
        "image": environment.assets.images.newsArticle2,
        "content": "<p>Now you have the ability to leave a game. The game you have left will no longer appear on \"My Games\" page. All you characters will be suspended." +
            "You can rejoin the game at any time, however the creator of the game will have to manually reactivate your characters.</p>" +
            "<p>Additionaly, all new characters are now created as \"Peding\", and the creator of the game has the ability to activate them.</p>",
        "date": "2025-02-25"
      },
      {
        "id": 2,
        "name": "Drafts and Autosave",
        "image": environment.assets.images.newsArticle2,
        "content": "<p>Now, when you are writing a post, it will automatically save as a draft every minute. Additionally," +
            "you can save the draft manually at any moment. For the autogenerated drafts, only the last five versions are kept," +
            "and everything older than five minutes is discarded. For the manually saved drafts, you may have as many as you want. " +
            "However, drafts are retained for thirty days only and then deleted.</p>" +
            "<p>Drafts are nore designed to be a permanent storage for your posts!</p>",
        "date": "2025-02-11"
      },
      {
        "id": 1,
        "name": "Core Functionality Is Ready",
        "image": environment.assets.images.newsArticle1,
        "content": "<p>The core sight functionality is ready. We can create games, characters and episodes. There are some basic\n" +
            "                bb codes we can use in the posts. Only the limited amount of genres and fandoms have been added to the database at this point. You can\n" +
            "            request more, and I will gladly add them.There is the visibility setting in the game menu, but it does not affect anything at this point. All the\n" +
            "            games, for now, are visible to the registered users and only to the registered users.</p>\n" +
            "            <p>There is no registration at this point, and it will not be opened for the time being. All the new users\n" +
            "            will be added manually.</p>",
        "date": "2025-01-03"
      }
    ])
  }
}
