name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test -- --watch=false --browsers=ChromeHeadless
    
    - name: Build
      run: npm run build:prod
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/trole-frontend

  deploy:
    needs: build-and-test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    runs-on: ubuntu-latest
    
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: dist
        path: dist/trole-frontend
    
    - name: Deploy to production
      # This is a placeholder for your actual deployment step
      # Replace with your actual deployment method (e.g., AWS S3, Firebase, etc.)
      run: |
        echo "Deploying to production..."
        # Example for AWS S3 deployment (uncomment and configure as needed)
        # aws s3 sync dist/trole-frontend s3://your-bucket-name/ --delete
        
        # Example for Firebase deployment (uncomment and configure as needed)
        # npm install -g firebase-tools
        # firebase deploy --only hosting --token "${{ secrets.FIREBASE_TOKEN }}"